modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="eventtest"
version="1.0.0"
displayName="Event Test"
description=""

[[dependencies.eventtest]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eventtest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

