package com.tdjs.testmod.item;

import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.text.Text;
import net.minecraft.util.Hand;
import net.minecraft.util.Rarity;
import net.minecraft.util.TypedActionResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.sound.SoundCategory;
import net.minecraft.sound.SoundEvents;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import java.util.Set;
import net.minecraft.item.FoodComponent;

/**
 * Pickle — generated by fabricpy
 */
public class pickle extends Item {

    public pickle() {
        super(new Item.Settings().maxCount(64).rarity(Rarity.EPIC).food(new FoodComponent.Builder().hunger(4).saturationModifier(6f).alwaysEdible().build()));
    }


}
