"""
Fabric mod project generator.

Produces a complete Fabric 1.20.1 mod project:
  src/main/java/.../
    {ModId}.java            — Main mod class (ModInitializer)
    ModBlocks.java          — Block registry
    ModItems.java           — Item registry
    block/{BlockName}.java  — One file per Block subclass
    item/{ItemName}.java    — One file per Item subclass
    event/ModEvents.java    — All registered event handlers
    command/ModCommands.java— All registered commands
    mixin/{Name}Mixin.java  — All Mixin subclasses
  src/main/resources/
    fabric.mod.json
    {modid}.mixins.json
    assets/{modid}/lang/en_us.json
  build.gradle
  settings.gradle
  gradle.properties
"""

import json
import os
import shutil
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from fabricpy.mod import Mod

from fabricpy.compiler.transpiler import JavaTranspiler
from fabricpy.compiler.api_maps import (
    FABRIC_API_MAP, FABRIC_EXTRA_IMPORTS,
    FABRIC_EVENT_MAP,
)


def to_pascal(snake: str) -> str:
    return "".join(w.capitalize() for w in snake.split("_"))


def _write_text(path: Path, content: str):
    path.write_text(content, encoding="utf-8")


def _resource_ref(mod_id: str, ref: str, folder: str, default_id: str) -> str:
    if ref:
        if ":" in ref:
            return ref
        if "/" in ref:
            return f"{mod_id}:{ref}"
        return f"{mod_id}:{folder}/{ref}"
    return f"{mod_id}:{folder}/{default_id}"


def _copy_tree_if_exists(src: Path, dest: Path):
    if src.exists():
        shutil.copytree(src, dest, dirs_exist_ok=True)


def generate_fabric_project(mod: "Mod", project_dir: Path):
    """Generate a complete Fabric mod project tree under project_dir."""
    pkg = mod.package
    pkg_path = pkg.replace(".", "/")
    src = project_dir / "src" / "main"
    java_root = src / "java" / pkg_path
    res_root = src / "resources"

    java_root.mkdir(parents=True, exist_ok=True)
    res_root.mkdir(parents=True, exist_ok=True)

    transpiler = JavaTranspiler(FABRIC_API_MAP)

    _write_main_class(mod, java_root, pkg)
    _write_mod_blocks(mod, java_root, pkg)
    _write_mod_items(mod, java_root, pkg)
    _write_block_classes(mod, java_root, pkg, transpiler)
    _write_item_classes(mod, java_root, pkg, transpiler)
    _write_events(mod, java_root, pkg, transpiler)
    _write_commands(mod, java_root, pkg, transpiler)
    _write_mixins(mod, java_root, pkg, transpiler)
    _write_resources(mod, res_root, pkg)
    _write_gradle_files(mod, project_dir)

    print(f"[fabricpy] Fabric project generated at {project_dir}")


# ─────────────────────────────────────────────────────────────────────────── #
# Main mod class
# ─────────────────────────────────────────────────────────────────────────── #

def _write_main_class(mod: "Mod", java_root: Path, pkg: str):
    class_name = to_pascal(mod.mod_id)

    has_blocks = bool(mod._blocks)
    has_items = bool(mod._items)
    has_events = bool(mod._events)
    has_commands = bool(mod._commands)

    reg_lines = []
    if has_blocks:
        reg_lines.append(f"        ModBlocks.register();")
    if has_items:
        reg_lines.append(f"        ModItems.register();")
    if has_events:
        reg_lines.append(f"        ModEvents.register();")
    if has_commands:
        reg_lines.append(f"        ModCommands.register();")
    if not reg_lines:
        reg_lines.append("        // No registrations yet")

    imports = []
    if has_events:
        imports.append(f"import {pkg}.event.ModEvents;")
    if has_commands:
        imports.append(f"import {pkg}.command.ModCommands;")

    src = f"""\
package {pkg};

{chr(10).join(imports)}
import net.fabricmc.api.ModInitializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by fabricpy — https://github.com/fabricpy
 * Main entrypoint for {mod.name} v{mod.version}
 */
public class {class_name} implements ModInitializer {{
    public static final String MOD_ID = "{mod.mod_id}";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {{
{chr(10).join(reg_lines)}
    }}
}}
"""
    _write_text(java_root / f"{class_name}.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Block registry
# ─────────────────────────────────────────────────────────────────────────── #

def _write_mod_blocks(mod: "Mod", java_root: Path, pkg: str):
    if not mod._blocks:
        return

    pkg_block = f"{pkg}.block"
    imports = [f"import {pkg_block}.{b.get_class_name()};" for b in mod._blocks]
    registrations = []
    for b in mod._blocks:
        cn = b.get_class_name()
        bid = b.block_id
        registrations.append(
            f'    public static final {cn} {bid.upper()} = register("{bid}", new {cn}());'
        )

    block_item_regs = []
    for b in mod._blocks:
        if b.drops_self:
            bid = b.block_id
            block_item_regs.append(
                f'        Registry.register(Registries.ITEM, new Identifier({to_pascal(mod.mod_id)}.MOD_ID, "{bid}"), '
                f'new BlockItem({bid.upper()}, new Item.Settings()));'
            )

    src = f"""\
package {pkg};

import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
{chr(10).join(imports)}

/**
 * Registers all blocks for {mod.name}.
 */
public class ModBlocks {{
{chr(10).join(registrations)}

    private static <T extends Block> T register(String id, T block) {{
        Registry.register(Registries.BLOCK, new Identifier({to_pascal(mod.mod_id)}.MOD_ID, id), block);
        return block;
    }}

    public static void register() {{
        // Blocks are registered via static initializer above.
        // Register block items:
{chr(10).join(block_item_regs) if block_item_regs else "        // No block items"}
{chr(10).join([f"        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(entries -> entries.add({b.block_id.upper()}));" for b in mod._blocks])}
    }}
}}
"""
    _write_text(java_root / "ModBlocks.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Item registry
# ─────────────────────────────────────────────────────────────────────────── #

def _write_mod_items(mod: "Mod", java_root: Path, pkg: str):
    if not mod._items:
        return

    pkg_item = f"{pkg}.item"
    imports = [f"import {pkg_item}.{i.get_class_name()};" for i in mod._items]
    registrations = []
    for it in mod._items:
        cn = it.get_class_name()
        iid = it.item_id
        registrations.append(
            f'    public static final {cn} {iid.upper()} = register("{iid}", new {cn}());'
        )

    src = f"""\
package {pkg};

import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
{chr(10).join(imports)}

/**
 * Registers all items for {mod.name}.
 */
public class ModItems {{
{chr(10).join(registrations)}

    private static <T extends Item> T register(String id, T item) {{
        return Registry.register(Registries.ITEM, new Identifier({to_pascal(mod.mod_id)}.MOD_ID, id), item);
    }}

    public static void register() {{
        // Items registered via static fields above.
{chr(10).join([f"        ItemGroupEvents.modifyEntriesEvent(ItemGroups.INGREDIENTS).register(entries -> entries.add({it.item_id.upper()}));" for it in mod._items])}
    }}
}}
"""
    _write_text(java_root / "ModItems.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Individual Block classes
# ─────────────────────────────────────────────────────────────────────────── #

_SOUND_MAP = {
    "stone": "BlockSoundGroup.STONE",
    "wood": "BlockSoundGroup.WOOD",
    "sand": "BlockSoundGroup.SAND",
    "wool": "BlockSoundGroup.WOOL",
    "metal": "BlockSoundGroup.METAL",
    "glass": "BlockSoundGroup.GLASS",
    "grass": "BlockSoundGroup.GRASS",
    "gravel": "BlockSoundGroup.GRAVEL",
    "snow": "BlockSoundGroup.SNOW",
}


def _write_block_classes(mod: "Mod", java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._blocks:
        return
    block_dir = java_root / "block"
    block_dir.mkdir(exist_ok=True)

    for block in mod._blocks:
        _write_single_block(mod, block, block_dir, pkg, transpiler)


def _write_single_block(mod, block, block_dir: Path, pkg: str, transpiler: JavaTranspiler):
    cn = block.get_class_name()
    pkg_block = f"{pkg}.block"
    hooks = block.get_hooks()

    # Build FabricBlockSettings chain
    settings_chain = (
        f"FabricBlockSettings.create()"
        f".strength({block.hardness}f, {block.resistance}f)"
        f".luminance(state -> {block.luminance})"
        f".slipperiness({block.slipperiness}f)"
        f".sounds({_SOUND_MAP.get(block.sound_group, 'BlockSoundGroup.STONE')})"
    )
    if not block.collidable:
        settings_chain += ".noCollision()"
    if block.requires_tool:
        settings_chain += ".requiresTool()"
    if not block.opaque:
        settings_chain += ".nonOpaque()"

    # Generate hook methods
    method_blocks = []

    if "on_use" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_use"])
        )
        method_blocks.append(f"""\
    @Override
    public ActionResult onUse(BlockState state, World world, BlockPos pos,
                               PlayerEntity player, Hand hand, BlockHitResult hit) {{
        BlockPos soundPos = pos;
{body}
        return ActionResult.SUCCESS;
    }}""")

    if "on_place" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_place"])
        )
        method_blocks.append(f"""\
    @Override
    public void onPlaced(World world, BlockPos pos, BlockState state,
                         @Nullable LivingEntity placer, ItemStack itemStack) {{
        PlayerEntity player = placer instanceof PlayerEntity ? (PlayerEntity) placer : null;
        BlockPos soundPos = pos;
{body}
    }}""")

    if "on_break" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_break"])
        )
        method_blocks.append(f"""\
    @Override
    public void onBreak(World world, BlockPos pos, BlockState state, PlayerEntity player) {{
        BlockPos soundPos = pos;
{body}
        super.onBreak(world, pos, state, player);
    }}""")

    methods_str = "\n\n".join(method_blocks)

    src = f"""\
package {pkg_block};

import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.entity.LivingEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.ItemStack;
import net.minecraft.text.Text;
import net.minecraft.util.ActionResult;
import net.minecraft.util.Hand;
import net.minecraft.util.hit.BlockHitResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.sound.SoundCategory;
import net.minecraft.sound.SoundEvents;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.Nullable;
import java.util.Set;

/**
 * {block.get_display_name()} — generated by fabricpy
 */
public class {cn} extends Block {{

    public {cn}() {{
        super({settings_chain});
    }}

{methods_str}
}}
"""
    _write_text(block_dir / f"{cn}.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Individual Item classes
# ─────────────────────────────────────────────────────────────────────────── #

_RARITY_MAP = {
    "common": "Rarity.COMMON",
    "uncommon": "Rarity.UNCOMMON",
    "rare": "Rarity.RARE",
    "epic": "Rarity.EPIC",
}


def _write_item_classes(mod: "Mod", java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._items:
        return
    item_dir = java_root / "item"
    item_dir.mkdir(exist_ok=True)

    for item in mod._items:
        _write_single_item(mod, item, item_dir, pkg, transpiler)


def _write_single_item(mod, item, item_dir: Path, pkg: str, transpiler: JavaTranspiler):
    cn = item.get_class_name()
    pkg_item = f"{pkg}.item"
    hooks = item.get_hooks()

    settings_chain = f"new Item.Settings().maxCount({item.max_stack_size})"
    if item.max_damage > 0:
        settings_chain += f".maxDamage({item.max_damage})"
    rarity_java = _RARITY_MAP.get(item.rarity, "Rarity.COMMON")
    settings_chain += f".rarity({rarity_java})"
    if item.fireproof:
        settings_chain += ".fireproof()"
    if item.food_hunger > 0:
        settings_chain += (
            f".food(new FoodComponent.Builder()"
            f".hunger({item.food_hunger})"
            f".saturationModifier({item.food_saturation}f)"
            + (".alwaysEdible()" if item.food_always_edible else "")
            + ".build())"
        )

    method_blocks = []

    if "on_right_click" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_right_click"])
        )
        method_blocks.append(f"""\
    @Override
    public TypedActionResult<ItemStack> use(World world, PlayerEntity user, Hand hand) {{
        PlayerEntity player = user;
        ItemStack stack = user.getStackInHand(hand);
        BlockPos soundPos = user.getBlockPos();
{body}
        return TypedActionResult.success(stack);
    }}""")

    methods_str = "\n\n".join(method_blocks)

    src = f"""\
package {pkg_item};

import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.FoodComponent;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.text.Text;
import net.minecraft.util.Hand;
import net.minecraft.util.Rarity;
import net.minecraft.util.TypedActionResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.sound.SoundCategory;
import net.minecraft.sound.SoundEvents;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import java.util.Set;

/**
 * {item.get_display_name()} — generated by fabricpy
 */
public class {cn} extends Item {{

    public {cn}() {{
        super({settings_chain});
    }}

{methods_str}
}}
"""
    _write_text(item_dir / f"{cn}.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Events
# ─────────────────────────────────────────────────────────────────────────── #

def _write_events(mod: "Mod", java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._events:
        return
    event_dir = java_root / "event"
    event_dir.mkdir(exist_ok=True)

    main_class = to_pascal(mod.mod_id)
    imports = set()
    register_blocks = []

    imports.add("import net.minecraft.server.network.ServerPlayerEntity;")
    imports.add("import net.minecraft.text.Text;")
    imports.add("import net.minecraft.registry.Registries;")
    imports.add("import net.minecraft.util.Identifier;")
    imports.add("import net.minecraft.item.ItemStack;")
    imports.add("import net.minecraft.sound.SoundCategory;")
    imports.add("import net.minecraft.sound.SoundEvents;")
    imports.add("import net.minecraft.server.world.ServerWorld;")
    imports.add("import net.minecraft.world.World;")
    imports.add("import net.minecraft.util.math.BlockPos;")
    imports.add("import java.util.Set;")

    for ev in mod._events:
        ev_name = ev["event"]
        ev_info = FABRIC_EVENT_MAP.get(ev_name)
        if not ev_info:
            register_blocks.append(f"        // Unknown event: {ev_name}")
            continue

        imports.add(ev_info["import"])
        body = transpiler.transpile_method(ev["source"])
        filled = ev_info["register"].format(body=body.strip())
        register_blocks.append(f"        {filled}")

    src = f"""\
package {pkg}.event;

{chr(10).join(sorted(imports))}

/**
 * Event registrations for {mod.name}.
 */
public class ModEvents {{

    public static void register() {{
{chr(10).join(register_blocks)}
    }}
}}
"""
    _write_text(event_dir / "ModEvents.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Commands
# ─────────────────────────────────────────────────────────────────────────── #

def _write_commands(mod: "Mod", java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._commands:
        return
    cmd_dir = java_root / "command"
    cmd_dir.mkdir(exist_ok=True)

    main_class = to_pascal(mod.mod_id)
    command_blocks = []

    for cmd in mod._commands:
        body = transpiler.transpile_method(cmd["source"])
        perm = cmd["permission_level"]
        perm_clause = ""
        if perm > 0:
            perm_clause = f".requires(source -> source.hasPermissionLevel({perm}))"

        command_blocks.append(f"""\
        dispatcher.register(CommandManager.literal("{cmd['name']}")
            {perm_clause}
            .executes(context -> {{
{body}
                return 1;
            }}));""")

        for alias in cmd.get("aliases", []):
            command_blocks.append(
                f'        dispatcher.register(CommandManager.literal("{alias}")'
                f'.redirect(dispatcher.getRoot().getChild("{cmd["name"]}")));'
            )

    src = f"""\
package {pkg}.command;

import com.mojang.brigadier.CommandDispatcher;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.minecraft.server.command.CommandManager;
import net.minecraft.server.command.ServerCommandSource;
import net.minecraft.text.Text;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import java.util.Set;

/**
 * Command registrations for {mod.name}.
 */
public class ModCommands {{

    public static void register() {{
        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) -> {{
{chr(10).join(command_blocks)}
        }});
    }}
}}
"""
    _write_text(cmd_dir / "ModCommands.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Mixins
# ─────────────────────────────────────────────────────────────────────────── #

def _write_mixins(mod: "Mod", java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._mixins:
        return
    mixin_dir = java_root / "mixin"
    mixin_dir.mkdir(exist_ok=True)

    for mx in mod._mixins:
        _write_single_mixin(mod, mx, mixin_dir, pkg, transpiler)


def _write_single_mixin(mod, mx, mixin_dir: Path, pkg: str, transpiler: JavaTranspiler):
    cn = mx.get_class_name()
    target = mx.target_class
    injections = mx.get_injections()
    method_blocks = []

    for method_name, func in injections.items():
        hook_args = func._fabricpy_hook_args
        target_method = hook_args.get("method", method_name)
        at = hook_args.get("at", "HEAD")
        cancellable = hook_args.get("cancellable", False)

        body = transpiler.transpile_method(
            __import__("inspect").getsource(func)
        )
        ci_param = ", CallbackInfo ci" if not cancellable else ", CallbackInfo ci /* cancellable */"
        method_blocks.append(f"""\
    @Inject(method = "{target_method}", at = @At("{at}"){', cancellable = true' if cancellable else ''})
    private void {method_name}({ci_param}) {{
{body}
    }}""")

    methods_str = "\n\n".join(method_blocks)

    src = f"""\
package {pkg}.mixin;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import net.minecraft.text.Text;
import net.minecraft.server.network.ServerPlayerEntity;
import java.util.Set;

/**
 * Mixin into {target} — generated by fabricpy
 */
@Mixin({target}.class)
public class {cn} {{

{methods_str}
}}
"""
    _write_text(mixin_dir / f"{cn}.java", src)


# ─────────────────────────────────────────────────────────────────────────── #
# Resources
# ─────────────────────────────────────────────────────────────────────────── #

def _write_resources(mod: "Mod", res_root: Path, pkg: str):
    main_class = f"{pkg}.{to_pascal(mod.mod_id)}"

    # fabric.mod.json
    fabric_mod = {
        "schemaVersion": 1,
        "id": mod.mod_id,
        "version": mod.version,
        "name": mod.name,
        "description": mod.description,
        "authors": mod.authors,
        "contact": {"homepage": mod.website} if mod.website else {},
        "license": mod.license,
        "environment": "*",
        "entrypoints": {"main": [main_class]},
        "depends": {
            "fabricloader": ">=0.14.22",
            "fabric-api": "*",
            "minecraft": f"~{mod.minecraft_version}",
            "java": ">=17",
        },
    }
    if mod._mixins:
        fabric_mod["mixins"] = [f"{mod.mod_id}.mixins.json"]
    _write_text(res_root / "fabric.mod.json", json.dumps(fabric_mod, indent=2))

    # mixins json
    if mod._mixins:
        mixin_pkg = f"{pkg}.mixin"
        mixin_classes = [mx.get_class_name() for mx in mod._mixins]
        mixins_json = {
            "required": True,
            "minVersion": "0.8",
            "package": mixin_pkg,
            "compatibilityLevel": "JAVA_17",
            "mixins": mixin_classes,
            "client": [],
            "injectors": {"defaultRequire": 1},
        }
        _write_text(res_root / f"{mod.mod_id}.mixins.json", json.dumps(mixins_json, indent=2))

    # en_us.json lang file
    lang = {}
    for b in mod._blocks:
        lang[f"block.{mod.mod_id}.{b.block_id}"] = b.get_display_name()
    for it in mod._items:
        lang[f"item.{mod.mod_id}.{it.item_id}"] = it.get_display_name()

    lang_dir = res_root / "assets" / mod.mod_id / "lang"
    lang_dir.mkdir(parents=True, exist_ok=True)
    _write_text(lang_dir / "en_us.json", json.dumps(lang, indent=2))

    blockstates_dir = res_root / "assets" / mod.mod_id / "blockstates"
    block_models_dir = res_root / "assets" / mod.mod_id / "models" / "block"
    item_models_dir = res_root / "assets" / mod.mod_id / "models" / "item"
    blockstates_dir.mkdir(parents=True, exist_ok=True)
    block_models_dir.mkdir(parents=True, exist_ok=True)
    item_models_dir.mkdir(parents=True, exist_ok=True)

    for block in mod._blocks:
        blockstate = block.blockstate or {
            "variants": {
                "": {"model": f"{mod.mod_id}:block/{block.block_id}"}
            }
        }
        block_model = block.model or {
            "parent": "minecraft:block/cube_all",
            "textures": block.textures or {
                "all": _resource_ref(mod.mod_id, block.texture, "block", block.block_id)
            }
        }
        block_item_model = block.item_model or {
            "parent": f"{mod.mod_id}:block/{block.block_id}"
        }
        _write_text(
            blockstates_dir / f"{block.block_id}.json",
            json.dumps(blockstate, indent=2),
        )
        _write_text(
            block_models_dir / f"{block.block_id}.json",
            json.dumps(block_model, indent=2),
        )
        _write_text(
            item_models_dir / f"{block.block_id}.json",
            json.dumps(block_item_model, indent=2),
        )

    for item in mod._items:
        item_model = item.model or {
            "parent": "minecraft:item/generated",
            "textures": item.textures or {
                "layer0": _resource_ref(mod.mod_id, item.texture, "item", item.item_id)
            }
        }
        _write_text(
            item_models_dir / f"{item.item_id}.json",
            json.dumps(item_model, indent=2),
        )

    recipes_dir = res_root / "data" / mod.mod_id / "recipes"
    recipes_dir.mkdir(parents=True, exist_ok=True)
    for recipe in mod._recipes:
        recipe_path = recipes_dir / f"{recipe['id']}.json"
        recipe_path.parent.mkdir(parents=True, exist_ok=True)
        _write_text(recipe_path, json.dumps(recipe["data"], indent=2))

    project_root = Path.cwd()
    _copy_tree_if_exists(project_root / "assets" / mod.mod_id, res_root / "assets" / mod.mod_id)
    _copy_tree_if_exists(project_root / "data" / mod.mod_id, res_root / "data" / mod.mod_id)

    # pack.mcmeta
    _write_text(res_root / "pack.mcmeta", json.dumps({
        "pack": {
            "pack_format": 15,
            "description": f"{mod.name} resources",
        }
    }, indent=2))


# ─────────────────────────────────────────────────────────────────────────── #
# Gradle build files
# ─────────────────────────────────────────────────────────────────────────── #

def _write_gradle_files(mod: "Mod", project_dir: Path):
    mc = mod.minecraft_version
    # Fabric versions for 1.20.1
    version_map = {
        "1.20.1": {
            "loom": "1.6-SNAPSHOT",
            "fabric_loader": "0.14.22",
            "fabric_api": "0.91.1+1.20.1",
            "yarn": "1.20.1+build.10",
        },
        "1.20.4": {
            "loom": "1.6-SNAPSHOT",
            "fabric_loader": "0.15.6",
            "fabric_api": "0.96.11+1.20.4",
            "yarn": "1.20.4+build.3",
        },
    }
    v = version_map.get(mc, version_map["1.20.1"])
    main_class = to_pascal(mod.mod_id)

    # build.gradle
    build_gradle = f"""\
plugins {{
    id 'fabric-loom' version '{v["loom"]}'
    id 'maven-publish'
}}

version = "{mod.version}"
group = "{mod.package}"

base {{
    archivesName = "{mod.mod_id}"
}}

repositories {{
    maven {{ url = "https://maven.fabricmc.net/" }}
    mavenCentral()
}}

dependencies {{
    minecraft "com.mojang:minecraft:{mc}"
    mappings "net.fabricmc:yarn:{v['yarn']}:v2"
    modImplementation "net.fabricmc:fabric-loader:{v['fabric_loader']}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:{v['fabric_api']}"
}}

processResources {{
    inputs.property "version", version

    filesMatching("fabric.mod.json") {{
        expand "version": version
    }}
}}

tasks.withType(JavaCompile).configureEach {{
    it.options.release = 17
}}

java {{
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}}

jar {{
    from("LICENSE") {{
        rename {{ "${{it}}_${{base.archivesName.get()}}" }}
    }}
}}
"""
    _write_text(project_dir / "build.gradle", build_gradle)

    # settings.gradle
    _write_text(project_dir / "settings.gradle", f"""\
pluginManagement {{
    repositories {{
        maven {{ url = "https://maven.fabricmc.net/" }}
        mavenCentral()
        gradlePluginPortal()
    }}
}}
rootProject.name = "{mod.mod_id}"
""")

    # gradle.properties
    _write_text(project_dir / "gradle.properties", f"""\
org.gradle.jvmargs=-Xmx1G
""")

    # .gitignore
    _write_text(project_dir / ".gitignore", ".gradle/\nbuild/\n*.jar\n!gradle/wrapper/gradle-wrapper.jar\n")
