"""
Forge mod project generator.

Produces a complete Forge 1.20.1 mod project:
  src/main/java/.../
    {ModId}.java                — @Mod main class
    ModBlocks.java              — DeferredRegister for blocks
    ModItems.java               — DeferredRegister for items
    block/{BlockName}.java      — One per Block subclass
    item/{ItemName}.java        — One per Item subclass
    event/ModEvents.java        — @SubscribeEvent handlers
    command/ModCommands.java    — RegisterCommandsEvent + Brigadier
  src/main/resources/
    META-INF/mods.toml
    pack.mcmeta
    assets/{modid}/lang/en_us.json
  build.gradle
  settings.gradle
  gradle.properties
"""

import json
import os
import shutil
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from fabricpy.mod import Mod

from fabricpy.compiler.transpiler import JavaTranspiler
from fabricpy.compiler.api_maps import (
    FORGE_API_MAP, FORGE_EXTRA_IMPORTS,
    FORGE_EVENT_MAP,
)


def to_pascal(snake: str) -> str:
    return "".join(w.capitalize() for w in snake.split("_"))


def _write_text(path: Path, content: str):
    path.write_text(content, encoding="utf-8")


def _resource_ref(mod_id: str, ref: str, folder: str, default_id: str) -> str:
    if ref:
        if ":" in ref:
            return ref
        if "/" in ref:
            return f"{mod_id}:{ref}"
        return f"{mod_id}:{folder}/{ref}"
    return f"{mod_id}:{folder}/{default_id}"


def _copy_tree_if_exists(src: Path, dest: Path):
    if src.exists():
        shutil.copytree(src, dest, dirs_exist_ok=True)


def generate_forge_project(mod: "Mod", project_dir: Path):
    """Generate a complete Forge mod project tree under project_dir."""
    pkg = mod.package
    pkg_path = pkg.replace(".", "/")
    src = project_dir / "src" / "main"
    java_root = src / "java" / pkg_path
    res_root = src / "resources"

    java_root.mkdir(parents=True, exist_ok=True)
    res_root.mkdir(parents=True, exist_ok=True)

    transpiler = JavaTranspiler(FORGE_API_MAP)

    _write_main_class(mod, java_root, pkg)
    _write_mod_blocks(mod, java_root, pkg)
    _write_mod_items(mod, java_root, pkg)
    _write_block_classes(mod, java_root, pkg, transpiler)
    _write_item_classes(mod, java_root, pkg, transpiler)
    _write_events(mod, java_root, pkg, transpiler)
    _write_commands(mod, java_root, pkg, transpiler)
    _write_resources(mod, res_root)
    _write_gradle_files(mod, project_dir)

    print(f"[fabricpy] Forge project generated at {project_dir}")


def _write_main_class(mod, java_root: Path, pkg: str):
    class_name = to_pascal(mod.mod_id)
    pkg_block = f"{pkg}.block" if mod._blocks else None
    pkg_item = f"{pkg}.item" if mod._items else None

    imports = []
    if mod._commands:
        imports.append(f"import {pkg}.command.ModCommands;")
    if mod._events:
        imports.append(f"import {pkg}.event.ModEvents;")

    src = f"""\
package {pkg};

{chr(10).join(imports)}
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.eventbus.api.IEventBus;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Generated by fabricpy — {mod.name} v{mod.version}
 */
@Mod("{mod.mod_id}")
public class {class_name} {{
    public static final String MOD_ID = "{mod.mod_id}";
    public static final Logger LOGGER = LogManager.getLogger(MOD_ID);

    public {class_name}() {{
        IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus();

        {"ModBlocks.BLOCKS.register(bus);" if mod._blocks else "// No blocks"}
        {"ModItems.ITEMS.register(bus);" if mod._items else "// No items"}
        {"bus.addListener(ModEvents::onCommonSetup);" if mod._events else "// No events"}
        {"bus.addListener(ModBlocks::addCreative);" if mod._blocks else ""}
        {"bus.addListener(ModItems::addCreative);" if mod._items else ""}

        // Register command events on Forge's main bus
        {"net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(ModCommands.class);" if mod._commands else "// No commands"}
        {"net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(ModEvents.class);" if mod._events else ""}
    }}
}}
"""
    _write_text(java_root / f"{class_name}.java", src)


def _write_mod_blocks(mod, java_root: Path, pkg: str):
    if not mod._blocks:
        return

    pkg_block = f"{pkg}.block"
    imports = [f"import {pkg_block}.{b.get_class_name()};" for b in mod._blocks]
    reg_lines = []
    for b in mod._blocks:
        cn = b.get_class_name()
        bid = b.block_id
        reg_lines.append(
            f'    public static final RegistryObject<Block> {bid.upper()} = '
            f'BLOCKS.register("{bid}", {cn}::new);'
        )
    block_item_lines = []
    for b in mod._blocks:
        if b.drops_self:
            bid = b.block_id
            block_item_lines.append(
                f'    public static final RegistryObject<Item> {bid.upper()}_ITEM = '
                f'ITEMS.register("{bid}", () -> new BlockItem({bid.upper()}.get(), new Item.Properties()));'
            )

    src = f"""\
package {pkg};

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
{chr(10).join(imports)}

public class ModBlocks {{
    public static final DeferredRegister<Block> BLOCKS =
        DeferredRegister.create(ForgeRegistries.BLOCKS, {to_pascal(mod.mod_id)}.MOD_ID);
    public static final DeferredRegister<Item> ITEMS =
        DeferredRegister.create(ForgeRegistries.ITEMS, {to_pascal(mod.mod_id)}.MOD_ID);

{chr(10).join(reg_lines)}
{chr(10).join(block_item_lines)}

    public static void addCreative(BuildCreativeModeTabContentsEvent event) {{
        if (event.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {{
{chr(10).join([f"            event.accept({b.block_id.upper()}_ITEM);" for b in mod._blocks if b.drops_self]) if any(b.drops_self for b in mod._blocks) else "            // No block items"}
        }}
    }}
}}
"""
    _write_text(java_root / "ModBlocks.java", src)


def _write_mod_items(mod, java_root: Path, pkg: str):
    if not mod._items:
        return

    pkg_item = f"{pkg}.item"
    imports = [f"import {pkg_item}.{i.get_class_name()};" for i in mod._items]
    reg_lines = []
    for it in mod._items:
        cn = it.get_class_name()
        iid = it.item_id
        reg_lines.append(
            f'    public static final RegistryObject<Item> {iid.upper()} = '
            f'ITEMS.register("{iid}", {cn}::new);'
        )

    src = f"""\
package {pkg};

import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
{chr(10).join(imports)}

public class ModItems {{
    public static final DeferredRegister<Item> ITEMS =
        DeferredRegister.create(ForgeRegistries.ITEMS, {to_pascal(mod.mod_id)}.MOD_ID);

{chr(10).join(reg_lines)}

    public static void addCreative(BuildCreativeModeTabContentsEvent event) {{
        if (event.getTabKey() == CreativeModeTabs.INGREDIENTS) {{
{chr(10).join([f"            event.accept({it.item_id.upper()});" for it in mod._items])}
        }}
    }}
}}
"""
    _write_text(java_root / "ModItems.java", src)


def _write_block_classes(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._blocks:
        return
    block_dir = java_root / "block"
    block_dir.mkdir(exist_ok=True)
    for block in mod._blocks:
        _write_single_block(mod, block, block_dir, pkg, transpiler)


def _write_single_block(mod, block, block_dir: Path, pkg: str, transpiler: JavaTranspiler):
    cn = block.get_class_name()
    hooks = block.get_hooks()

    settings = (
        f"BlockBehaviour.Properties.of()"
        f".strength({block.hardness}f, {block.resistance}f)"
        f".lightLevel(state -> {block.luminance})"
        f".friction({block.slipperiness}f)"
    )
    if not block.collidable:
        settings += ".noCollision()"
    if block.requires_tool:
        settings += ".requiresCorrectToolForDrops()"
    if not block.opaque:
        settings += ".noOcclusion()"

    method_blocks = []

    if "on_use" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_use"])
        )
        method_blocks.append(f"""\
    @Override
    public InteractionResult use(BlockState state, Level level, BlockPos pos,
                                  Player player, InteractionHand hand, BlockHitResult hit) {{
        BlockPos soundPos = pos;
{body}
        return InteractionResult.SUCCESS;
    }}""")

    if "on_place" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_place"])
        )
        method_blocks.append(f"""\
    @Override
    public void setPlacedBy(Level level, BlockPos pos, BlockState state,
                             @Nullable LivingEntity placer, ItemStack stack) {{
        Player player = placer instanceof Player ? (Player) placer : null;
        BlockPos soundPos = pos;
{body}
    }}""")

    if "on_break" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_break"])
        )
        method_blocks.append(f"""\
    @Override
    public void playerDestroy(Level level, Player player, BlockPos pos, BlockState state,
                               @Nullable BlockEntity te, ItemStack stack) {{
        BlockPos soundPos = pos;
{body}
        super.playerDestroy(level, player, pos, state, te, stack);
    }}""")

    methods_str = "\n\n".join(method_blocks)

    src = f"""\
package {pkg}.block;

import net.minecraft.core.BlockPos;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;
import org.jetbrains.annotations.Nullable;

/**
 * {block.get_display_name()} — generated by fabricpy
 */
public class {cn} extends Block {{

    public {cn}() {{
        super({settings});
    }}

{methods_str}
}}
"""
    _write_text(block_dir / f"{cn}.java", src)


def _write_item_classes(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._items:
        return
    item_dir = java_root / "item"
    item_dir.mkdir(exist_ok=True)
    for item in mod._items:
        _write_single_item(mod, item, item_dir, pkg, transpiler)


def _write_single_item(mod, item, item_dir: Path, pkg: str, transpiler: JavaTranspiler):
    cn = item.get_class_name()
    hooks = item.get_hooks()

    settings = f"new Item.Properties().stacksTo({item.max_stack_size})"
    if item.max_damage > 0:
        settings += f".durability({item.max_damage})"
    if item.fireproof:
        settings += ".fireResistant()"

    method_blocks = []
    if "on_right_click" in hooks:
        body = transpiler.transpile_method(
            __import__("inspect").getsource(hooks["on_right_click"])
        )
        method_blocks.append(f"""\
    @Override
    public InteractionResultHolder<ItemStack> use(Level level, Player user, InteractionHand hand) {{
        Player player = user;
        ItemStack stack = user.getItemInHand(hand);
        BlockPos soundPos = user.blockPosition();
{body}
        return InteractionResultHolder.success(stack);
    }}""")

    methods_str = "\n\n".join(method_blocks)

    src = f"""\
package {pkg}.item;

import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.level.Level;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;

/**
 * {item.get_display_name()} — generated by fabricpy
 */
public class {cn} extends Item {{

    public {cn}() {{
        super({settings});
    }}

{methods_str}
}}
"""
    _write_text(item_dir / f"{cn}.java", src)


def _write_events(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._events:
        return
    event_dir = java_root / "event"
    event_dir.mkdir(exist_ok=True)

    imports = set()
    imports.add("import net.minecraftforge.eventbus.api.SubscribeEvent;")
    imports.add("import net.minecraftforge.fml.common.Mod;")
    imports.add("import net.minecraft.world.entity.player.Player;")
    imports.add("import net.minecraft.network.chat.Component;")
    imports.add("import net.minecraft.server.level.ServerPlayer;")

    method_blocks = []

    for ev in mod._events:
        ev_name = ev["event"]
        ev_info = FORGE_EVENT_MAP.get(ev_name)
        if not ev_info:
            method_blocks.append(f"    // Unknown event: {ev_name}")
            continue

        imports.add(ev_info["import"])
        body = transpiler.transpile_method(ev["source"])

        setup_line = ev_info.get("setup", "")
        local_lines = "\n".join(ev_info.get("locals", []))
        if not local_lines and ev_info.get("player_expr"):
            local_lines = f"        Player player = {ev_info['player_expr']};"

        method_blocks.append(f"""\
    @SubscribeEvent
    public static void on{to_pascal(ev_name)}({ev_info['class']} event) {{
{setup_line}
{local_lines}
{body}
    }}""")

    src = f"""\
package {pkg}.event;

import {pkg}.{to_pascal(mod.mod_id)};
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
{chr(10).join(sorted(imports))}

@Mod.EventBusSubscriber(modid = {to_pascal(mod.mod_id)}.MOD_ID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class ModEvents {{

    public static void onCommonSetup(FMLCommonSetupEvent event) {{
        // Common setup
    }}

{chr(10).join(method_blocks)}
}}
"""
    _write_text(event_dir / "ModEvents.java", src)


def _write_commands(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._commands:
        return
    cmd_dir = java_root / "command"
    cmd_dir.mkdir(exist_ok=True)

    command_blocks = []
    for cmd in mod._commands:
        body = transpiler.transpile_method(cmd["source"])
        perm = cmd["permission_level"]
        perm_clause = f".requires(s -> s.hasPermission({perm}))" if perm > 0 else ""
        command_blocks.append(f"""\
        event.getDispatcher().register(Commands.literal("{cmd['name']}")
            {perm_clause}
            .executes(context -> {{
{body}
                return 1;
            }}));""")

    src = f"""\
package {pkg}.command;

import {pkg}.{to_pascal(mod.mod_id)};
import com.mojang.brigadier.context.CommandContext;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.event.RegisterCommandsEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(modid = {to_pascal(mod.mod_id)}.MOD_ID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class ModCommands {{

    @SubscribeEvent
    public static void onRegisterCommands(RegisterCommandsEvent event) {{
{chr(10).join(command_blocks)}
    }}
}}
"""
    _write_text(cmd_dir / "ModCommands.java", src)


def _write_resources(mod, res_root: Path):
    # META-INF/mods.toml
    meta_dir = res_root / "META-INF"
    meta_dir.mkdir(parents=True, exist_ok=True)

    deps = f"""
[[dependencies.{mod.mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.{mod.mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[{mod.minecraft_version},)"
    ordering="NONE"
    side="BOTH"
"""

    mods_toml = f"""\
modLoader="javafml"
loaderVersion="[47,)"
license="{mod.license}"

[[mods]]
modId="{mod.mod_id}"
version="{mod.version}"
displayName="{mod.name}"
description="{mod.description}"
{deps}
"""
    _write_text(meta_dir / "mods.toml", mods_toml)

    # pack.mcmeta
    _write_text(res_root / "pack.mcmeta", json.dumps({
        "pack": {"pack_format": 15, "description": f"{mod.name} resources"}
    }, indent=2))

    # lang
    lang = {}
    for b in mod._blocks:
        lang[f"block.{mod.mod_id}.{b.block_id}"] = b.get_display_name()
    for it in mod._items:
        lang[f"item.{mod.mod_id}.{it.item_id}"] = it.get_display_name()
    lang_dir = res_root / "assets" / mod.mod_id / "lang"
    lang_dir.mkdir(parents=True, exist_ok=True)
    _write_text(lang_dir / "en_us.json", json.dumps(lang, indent=2))

    blockstates_dir = res_root / "assets" / mod.mod_id / "blockstates"
    block_models_dir = res_root / "assets" / mod.mod_id / "models" / "block"
    item_models_dir = res_root / "assets" / mod.mod_id / "models" / "item"
    blockstates_dir.mkdir(parents=True, exist_ok=True)
    block_models_dir.mkdir(parents=True, exist_ok=True)
    item_models_dir.mkdir(parents=True, exist_ok=True)

    for block in mod._blocks:
        blockstate = block.blockstate or {
            "variants": {
                "": {"model": f"{mod.mod_id}:block/{block.block_id}"}
            }
        }
        block_model = block.model or {
            "parent": "minecraft:block/cube_all",
            "textures": block.textures or {
                "all": _resource_ref(mod.mod_id, block.texture, "block", block.block_id)
            }
        }
        block_item_model = block.item_model or {
            "parent": f"{mod.mod_id}:block/{block.block_id}"
        }
        _write_text(
            blockstates_dir / f"{block.block_id}.json",
            json.dumps(blockstate, indent=2),
        )
        _write_text(
            block_models_dir / f"{block.block_id}.json",
            json.dumps(block_model, indent=2),
        )
        _write_text(
            item_models_dir / f"{block.block_id}.json",
            json.dumps(block_item_model, indent=2),
        )

    for item in mod._items:
        item_model = item.model or {
            "parent": "minecraft:item/generated",
            "textures": item.textures or {
                "layer0": _resource_ref(mod.mod_id, item.texture, "item", item.item_id)
            }
        }
        _write_text(
            item_models_dir / f"{item.item_id}.json",
            json.dumps(item_model, indent=2),
        )

    recipes_dir = res_root / "data" / mod.mod_id / "recipes"
    recipes_dir.mkdir(parents=True, exist_ok=True)
    for recipe in mod._recipes:
        recipe_path = recipes_dir / f"{recipe['id']}.json"
        recipe_path.parent.mkdir(parents=True, exist_ok=True)
        _write_text(recipe_path, json.dumps(recipe["data"], indent=2))

    project_root = Path.cwd()
    _copy_tree_if_exists(project_root / "assets" / mod.mod_id, res_root / "assets" / mod.mod_id)
    _copy_tree_if_exists(project_root / "data" / mod.mod_id, res_root / "data" / mod.mod_id)


def _write_gradle_files(mod, project_dir: Path):
    mc = mod.minecraft_version
    forge_version_map = {
        "1.20.1": "47.2.20",
        "1.20.4": "49.0.19",
    }
    forge_ver = forge_version_map.get(mc, "47.2.20")
    main_class = to_pascal(mod.mod_id)

    build_gradle = f"""\
buildscript {{
    repositories {{
        maven {{ url = 'https://maven.minecraftforge.net' }}
        mavenCentral()
    }}
    dependencies {{
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.+'
    }}
}}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'

version = "{mod.version}"
group = "{mod.package}"

java {{
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}}

minecraft {{
    mappings channel: 'official', version: '{mc}'

    runs {{
        client {{
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods {{
                {mod.mod_id} {{
                    source sourceSets.main
                }}
            }}
        }}
        server {{
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods {{
                {mod.mod_id} {{
                    source sourceSets.main
                }}
            }}
        }}
    }}
}}

repositories {{
    mavenCentral()
}}

dependencies {{
    minecraft 'net.minecraftforge:forge:{mc}-{forge_ver}'
}}

jar {{
    manifest {{
        attributes([
            "Specification-Title"  : "{mod.mod_id}",
            "Specification-Vendor" : "{', '.join(mod.authors) if mod.authors else 'Unknown'}",
            "Specification-Version": "1",
            "Implementation-Title" : project.name,
            "Implementation-Version": project.version,
            "Implementation-Vendor": "{', '.join(mod.authors) if mod.authors else 'Unknown'}",
        ])
    }}
}}
"""
    _write_text(project_dir / "build.gradle", build_gradle)

    _write_text(project_dir / "settings.gradle", f'rootProject.name = "{mod.mod_id}-forge"\n')
    _write_text(project_dir / "gradle.properties", "org.gradle.jvmargs=-Xmx2G\n")
    _write_text(project_dir / ".gitignore", ".gradle/\nbuild/\nrun/\n*.jar\n")
