"""
NeoForge mod project generator.
"""

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from fabricpy.mod import Mod

import fabricpy.compiler.forge_gen as forge_gen
from fabricpy.compiler.api_maps import NEOFORGE_API_MAP, NEOFORGE_EVENT_MAP
from fabricpy.compiler.transpiler import JavaTranspiler


def generate_neoforge_project(mod: "Mod", project_dir: Path):
    pkg = mod.package
    pkg_path = pkg.replace(".", "/")
    src = project_dir / "src" / "main"
    java_root = src / "java" / pkg_path
    res_root = src / "resources"

    java_root.mkdir(parents=True, exist_ok=True)
    res_root.mkdir(parents=True, exist_ok=True)

    transpiler = JavaTranspiler(NEOFORGE_API_MAP)

    _write_main_class(mod, java_root, pkg)
    _write_mod_blocks(mod, java_root, pkg)
    _write_mod_items(mod, java_root, pkg)
    _write_block_classes(mod, java_root, pkg, transpiler)
    _write_item_classes(mod, java_root, pkg, transpiler)
    _write_events(mod, java_root, pkg, transpiler)
    _write_commands(mod, java_root, pkg, transpiler)
    _write_neoforge_resources(mod, res_root)
    _write_neoforge_gradle_files(mod, project_dir)

    print(f"[fabricpy] NeoForge project generated at {project_dir}")


def _write_main_class(mod, java_root: Path, pkg: str):
    class_name = forge_gen.to_pascal(mod.mod_id)
    imports = []
    if mod._events:
        imports.append(f"import {pkg}.event.ModEvents;")
    if mod._commands:
        imports.append(f"import {pkg}.command.ModCommands;")

    src = f"""\
package {pkg};

{chr(10).join(imports)}
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Generated by fabricpy - {mod.name} v{mod.version}
 */
@Mod("{mod.mod_id}")
public class {class_name} {{
    public static final String MOD_ID = "{mod.mod_id}";
    public static final Logger LOGGER = LogManager.getLogger(MOD_ID);

    public {class_name}(IEventBus modEventBus) {{
        {"ModBlocks.BLOCKS.register(modEventBus);" if mod._blocks else "// No blocks"}
        {"ModBlocks.ITEMS.register(modEventBus);" if mod._blocks and any(b.drops_self for b in mod._blocks) else ""}
        {"ModItems.ITEMS.register(modEventBus);" if mod._items else "// No items"}
        {"modEventBus.addListener(ModEvents::onCommonSetup);" if mod._events else "// No events"}
        {"modEventBus.addListener(ModBlocks::addCreative);" if mod._blocks else ""}
        {"modEventBus.addListener(ModItems::addCreative);" if mod._items else ""}
    }}
}}
"""
    forge_gen._write_text(java_root / f"{class_name}.java", src)


def _write_mod_blocks(mod, java_root: Path, pkg: str):
    if not mod._blocks:
        return

    pkg_block = f"{pkg}.block"
    imports = [f"import {pkg_block}.{b.get_class_name()};" for b in mod._blocks]
    reg_lines = []
    for block in mod._blocks:
        cn = block.get_class_name()
        bid = block.block_id
        reg_lines.append(
            f'    public static final DeferredHolder<Block, Block> {bid.upper()} = '
            f'BLOCKS.register("{bid}", {cn}::new);'
        )

    block_item_lines = []
    for block in mod._blocks:
        if block.drops_self:
            bid = block.block_id
            block_item_lines.append(
                f'    public static final DeferredHolder<Item, Item> {bid.upper()}_ITEM = '
                f'ITEMS.register("{bid}", () -> new BlockItem({bid.upper()}.get(), new Item.Properties()));'
            )

    src = f"""\
package {pkg};

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
{chr(10).join(imports)}

public class ModBlocks {{
    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks({forge_gen.to_pascal(mod.mod_id)}.MOD_ID);
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems({forge_gen.to_pascal(mod.mod_id)}.MOD_ID);

{chr(10).join(reg_lines)}
{chr(10).join(block_item_lines)}

    public static void addCreative(BuildCreativeModeTabContentsEvent event) {{
        if (event.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {{
{chr(10).join([f"            event.accept({b.block_id.upper()}_ITEM.get());" for b in mod._blocks if b.drops_self]) if any(b.drops_self for b in mod._blocks) else "            // No block items"}
        }}
    }}
}}
"""
    forge_gen._write_text(java_root / "ModBlocks.java", src)


def _write_mod_items(mod, java_root: Path, pkg: str):
    if not mod._items:
        return

    pkg_item = f"{pkg}.item"
    imports = [f"import {pkg_item}.{i.get_class_name()};" for i in mod._items]
    reg_lines = []
    for item in mod._items:
        cn = item.get_class_name()
        iid = item.item_id
        reg_lines.append(
            f'    public static final DeferredHolder<Item, Item> {iid.upper()} = '
            f'ITEMS.register("{iid}", {cn}::new);'
        )

    src = f"""\
package {pkg};

import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
{chr(10).join(imports)}

public class ModItems {{
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems({forge_gen.to_pascal(mod.mod_id)}.MOD_ID);

{chr(10).join(reg_lines)}

    public static void addCreative(BuildCreativeModeTabContentsEvent event) {{
        if (event.getTabKey() == CreativeModeTabs.INGREDIENTS) {{
{chr(10).join([f"            event.accept({it.item_id.upper()}.get());" for it in mod._items])}
        }}
    }}
}}
"""
    forge_gen._write_text(java_root / "ModItems.java", src)


def _write_block_classes(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._blocks:
        return
    block_dir = java_root / "block"
    block_dir.mkdir(exist_ok=True)
    for block in mod._blocks:
        _write_single_block(block, block_dir, pkg, transpiler)


def _write_single_block(block, block_dir: Path, pkg: str, transpiler: JavaTranspiler):
    cn = block.get_class_name()
    hooks = block.get_hooks()

    settings = (
        f"BlockBehaviour.Properties.of()"
        f".strength({block.hardness}f, {block.resistance}f)"
        f".lightLevel(state -> {block.luminance})"
        f".friction({block.slipperiness}f)"
    )
    if not block.collidable:
        settings += ".noCollision()"
    if block.requires_tool:
        settings += ".requiresCorrectToolForDrops()"
    if not block.opaque:
        settings += ".noOcclusion()"

    method_blocks = []

    if "on_use" in hooks:
        body = transpiler.transpile_method(__import__("inspect").getsource(hooks["on_use"]))
        method_blocks.append(f"""\
    @Override
    public InteractionResult use(BlockState state, Level level, BlockPos pos,
                                  Player player, InteractionHand hand, BlockHitResult hit) {{
        BlockPos soundPos = pos;
{body}
        return InteractionResult.SUCCESS;
    }}""")

    if "on_place" in hooks:
        body = transpiler.transpile_method(__import__("inspect").getsource(hooks["on_place"]))
        method_blocks.append(f"""\
    @Override
    public void setPlacedBy(Level level, BlockPos pos, BlockState state,
                             @org.jetbrains.annotations.Nullable LivingEntity placer, ItemStack stack) {{
        Player player = placer instanceof Player ? (Player) placer : null;
        BlockPos soundPos = pos;
{body}
    }}""")

    if "on_break" in hooks:
        body = transpiler.transpile_method(__import__("inspect").getsource(hooks["on_break"]))
        method_blocks.append(f"""\
    @Override
    public void playerDestroy(Level level, Player player, BlockPos pos, BlockState state,
                               @org.jetbrains.annotations.Nullable BlockEntity te, ItemStack stack) {{
        BlockPos soundPos = pos;
{body}
        super.playerDestroy(level, player, pos, state, te, stack);
    }}""")

    src = f"""\
package {pkg}.block;

import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;

/**
 * {block.get_display_name()} - generated by fabricpy
 */
public class {cn} extends Block {{

    public {cn}() {{
        super({settings});
    }}

{chr(10).join(method_blocks)}
}}
"""
    forge_gen._write_text(block_dir / f"{cn}.java", src)


def _write_item_classes(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._items:
        return
    item_dir = java_root / "item"
    item_dir.mkdir(exist_ok=True)
    for item in mod._items:
        _write_single_item(item, item_dir, pkg, transpiler)


def _write_single_item(item, item_dir: Path, pkg: str, transpiler: JavaTranspiler):
    cn = item.get_class_name()
    hooks = item.get_hooks()

    settings = f"new Item.Properties().stacksTo({item.max_stack_size})"
    if item.max_damage > 0:
        settings += f".durability({item.max_damage})"
    if item.fireproof:
        settings += ".fireResistant()"

    method_blocks = []
    if "on_right_click" in hooks:
        body = transpiler.transpile_method(__import__("inspect").getsource(hooks["on_right_click"]))
        method_blocks.append(f"""\
    @Override
    public InteractionResultHolder<ItemStack> use(Level level, Player user, InteractionHand hand) {{
        Player player = user;
        ItemStack stack = user.getItemInHand(hand);
        BlockPos soundPos = user.blockPosition();
{body}
        return InteractionResultHolder.success(stack);
    }}""")

    src = f"""\
package {pkg}.item;

import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;

/**
 * {item.get_display_name()} - generated by fabricpy
 */
public class {cn} extends Item {{

    public {cn}() {{
        super({settings});
    }}

{chr(10).join(method_blocks)}
}}
"""
    forge_gen._write_text(item_dir / f"{cn}.java", src)


def _write_events(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._events:
        return
    event_dir = java_root / "event"
    event_dir.mkdir(exist_ok=True)

    imports = {
        "import net.minecraft.core.BlockPos;",
        "import net.minecraft.core.registries.BuiltInRegistries;",
        "import net.minecraft.network.chat.Component;",
        "import net.minecraft.resources.ResourceLocation;",
        "import net.minecraft.server.level.ServerPlayer;",
        "import net.minecraft.world.effect.MobEffectInstance;",
        "import net.minecraft.world.entity.player.Player;",
        "import net.minecraft.world.level.Level;",
        "import net.neoforged.bus.api.SubscribeEvent;",
        "import net.neoforged.fml.common.EventBusSubscriber;",
        "import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;",
    }

    method_blocks = []
    for ev in mod._events:
        ev_name = ev["event"]
        ev_info = NEOFORGE_EVENT_MAP.get(ev_name)
        if not ev_info:
            method_blocks.append(f"    // Unknown event: {ev_name}")
            continue

        imports.add(ev_info["import"])
        body = transpiler.transpile_method(ev["source"])
        setup_line = ev_info.get("setup", "")
        local_lines = "\n".join(ev_info.get("locals", []))

        method_blocks.append(f"""\
    @SubscribeEvent
    public static void on{forge_gen.to_pascal(ev_name)}({ev_info['class']} event) {{
{setup_line}
{local_lines}
{body}
    }}""")

    src = f"""\
package {pkg}.event;

import {pkg}.{forge_gen.to_pascal(mod.mod_id)};
{chr(10).join(sorted(imports))}

@EventBusSubscriber(modid = {forge_gen.to_pascal(mod.mod_id)}.MOD_ID)
public class ModEvents {{

    public static void onCommonSetup(FMLCommonSetupEvent event) {{
        // Common setup
    }}

{chr(10).join(method_blocks)}
}}
"""
    forge_gen._write_text(event_dir / "ModEvents.java", src)


def _write_commands(mod, java_root: Path, pkg: str, transpiler: JavaTranspiler):
    if not mod._commands:
        return
    cmd_dir = java_root / "command"
    cmd_dir.mkdir(exist_ok=True)

    command_blocks = []
    for cmd in mod._commands:
        body = transpiler.transpile_method(cmd["source"])
        perm = cmd["permission_level"]
        perm_clause = f".requires(s -> s.hasPermission({perm}))" if perm > 0 else ""
        command_blocks.append(f"""\
        event.getDispatcher().register(Commands.literal("{cmd['name']}")
            {perm_clause}
            .executes(context -> {{
{body}
                return 1;
            }}));""")

    src = f"""\
package {pkg}.command;

import {pkg}.{forge_gen.to_pascal(mod.mod_id)};
import com.mojang.brigadier.context.CommandContext;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.RegisterCommandsEvent;

@EventBusSubscriber(modid = {forge_gen.to_pascal(mod.mod_id)}.MOD_ID)
public class ModCommands {{

    @SubscribeEvent
    public static void onRegisterCommands(RegisterCommandsEvent event) {{
{chr(10).join(command_blocks)}
    }}
}}
"""
    forge_gen._write_text(cmd_dir / "ModCommands.java", src)


def _write_neoforge_resources(mod: "Mod", res_root: Path):
    forge_gen._write_resources(mod, res_root)

    meta_dir = res_root / "META-INF"
    mods_toml = meta_dir / "mods.toml"
    if mods_toml.exists():
        content = mods_toml.read_text(encoding="utf-8")
        content = content.replace('modId="forge"', 'modId="neoforge"')
        content = content.replace('loaderVersion="[47,)"', 'loaderVersion="[1,)"')
        content = content.replace('loaderVersion="[52,)"', 'loaderVersion="[1,)"')
        content = content.replace('versionRange="[47,)"', 'versionRange="[1,)"')
        content = content.replace('versionRange="[52,)"', 'versionRange="[1,)"')
        forge_gen._write_text(meta_dir / "neoforge.mods.toml", content)
        mods_toml.unlink()


def _write_neoforge_gradle_files(mod: "Mod", project_dir: Path):
    mc = mod.minecraft_version
    version_map = {
        "1.21.1": {
            "moddev": "1.0.11",
            "neoforge": "21.1.222",
            "java": 21,
            "settings_plugin": "1.0.0",
        },
    }
    if mc not in version_map:
        raise ValueError(f"NeoForge does not support minecraft_version={mc!r} in this generator.")
    v = version_map[mc]

    build_gradle = f"""\
plugins {{
    id 'net.neoforged.moddev' version '{v["moddev"]}'
}}

version = "{mod.version}"
group = "{mod.package}"

base {{
    archivesName = "{mod.mod_id}-neoforge"
}}

java {{
    toolchain.languageVersion = JavaLanguageVersion.of({v['java']})
}}

neoForge {{
    version = "{v['neoforge']}"
    runs {{
        client {{
            client()
        }}
        server {{
            server()
        }}
    }}
    mods {{
        {mod.mod_id} {{
            sourceSet sourceSets.main
        }}
    }}
}}

tasks.withType(JavaCompile).configureEach {{
    options.encoding = 'UTF-8'
}}
"""
    forge_gen._write_text(project_dir / "build.gradle", build_gradle)
    forge_gen._write_text(project_dir / "settings.gradle", f"""\
pluginManagement {{
    repositories {{
        gradlePluginPortal()
    }}
}}

plugins {{
    id 'org.gradle.toolchains.foojay-resolver-convention' version '{v["settings_plugin"]}'
}}

rootProject.name = "{mod.mod_id}-neoforge"
""")
    forge_gen._write_text(project_dir / "gradle.properties", "org.gradle.jvmargs=-Xmx2G\norg.gradle.configuration-cache=true\n")
    forge_gen._write_text(project_dir / ".gitignore", ".gradle/\nbuild/\nrun/\n*.jar\n!gradle/wrapper/gradle-wrapper.jar\n")
