modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="test"
version="1.0.0"
displayName="Test Mod"
description="A mod to test fabricpy"

[[dependencies.test]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

