package com.tdjs.testmod;

import com.tdjs.testmod.command.ModCommands;
import com.tdjs.testmod.event.ModEvents;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.eventbus.api.IEventBus;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Generated by fabricpy — Test Mod v1.0.0
 */
@Mod("test")
public class Test {
    public static final String MOD_ID = "test";
    public static final Logger LOGGER = LogManager.getLogger(MOD_ID);

    public Test() {
        IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus();

        ModBlocks.BLOCKS.register(bus);
        ModItems.ITEMS.register(bus);
        bus.addListener(ModEvents::onCommonSetup);
        bus.addListener(ModBlocks::addCreative);
        bus.addListener(ModItems::addCreative);

        // Register command events on Forge's main bus
        net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(ModCommands.class);
        net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(ModEvents.class);
    }
}
