package com.tdjs.testmod;

import com.tdjs.testmod.event.ModEvents;
import net.fabricmc.api.ModInitializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by fabricpy — https://github.com/fabricpy
 * Main entrypoint for Test Mod v1.0.0
 */
public class Test implements ModInitializer {
    public static final String MOD_ID = "test";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {
        ModBlocks.register();
        ModItems.register();
        ModEvents.register();
    }
}
